// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnpxaqjcojlgbjzgdyyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucHhhcWpjb2psZ2JqemdkeXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDE4MjksImV4cCI6MjA3MzQ3NzgyOX0.ZF1jF6wo1PkmpnHTZgaH1zWtRaXCTuPg7HnC0-JxoNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});